spring.application.name=SpringAIQuickStart

server.port=8080

# 配置 Deepseek URL、API Key、模型
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.api-key=sk-da11b9e08cd543b8afbf5110aac38ee6
spring.ai.deepseek.chat.options.model=deepseek-v4-flash

# 配置温度，范围0-2 2 发散
spring.ai.deepseek.chat.options.temperature=0.8

# 配置日志
logging.pattern.console= %-5level %logger - %msg%n

